language: python

python:
  - "3.4"
  - "3.5"

install:
  - python setup.py sdist install
  - pip install coveralls

# command to run tests
script:
    - coverage run --source=cltk_capitains_corpora_converter setup.py test
after_success:
    - coveralls